trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
# Restore dependencies
- script: |
    dotnet restore
  displayName: 'Restore dependencies'

# Build project
- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build $(buildConfiguration)'

# Execute unit tests with coverage-
- script: dotnet test $(Build.SourceDirectory)/POCOMapper.Test/POCOMapper.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
  displayName: 'Test with coverage'

# Publish coverage results
- task: PublishCodeCoverageResults@1
  displayName: 'Publish test coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourceDirectory)/**/coverage.cobertura.xml'
