trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
# Restore dependencies
- script: |
    dotnet restore
  displayName: 'Restore dependencies'

# Build project
- script: |
    dotnet build --configuration $(
  displayName: 'Build $(buildConfiguration)'

# Execute unit tests with coverage-
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'POCOMapper.Test/POCOMapper.Test.csproj'
    arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'

# Publish coverage results
- task: PublishCodeCoverageResults@1
  displayName: 'Publish test coverage'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourceDirectory)/**/coverage.cobertura.xml'
