name: .NET

on:
  push:
    branches:
      - 'prod'

jobs:
  publish:
    name: Build, Pack & Publish NuGet
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # Use specific .NET Version
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
        
    # Restore
    - name: Restore dependencies
      run: |
        cd ./POCOMapper
        dotnet restore
      
    # Build
    - name: Build
      run: |
        cd ./POCOMapper
        dotnet build --no-restore

    # Pack
    - name: Pack
      run:
        dotnet pack POCOMapper/POCOMapper.csproj -c Release
      
    # Publish
    - name: Publish
      run: dotnet nuget push /home/runner/work/poco.mapper/poco.mapper/POCOMapper/bin/Release/POCOMapper.*.nupkg --api-key ${{secrets.NUGET_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
